version: '3'

services:

  app:
    build:
      context: ./node
    container_name: app
    tty: true
    networks:
      - app-network
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=appdb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    tty: true
    networks:
      - app-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
